// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using order_api.Data;

#nullable disable

namespace order_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("order_api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("order_api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple",
                            Price = 10m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Name = "Banana",
                            Price = 5m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            Name = "Milk",
                            Price = 40m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bread",
                            Price = 30m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eggs (12 pcs)",
                            Price = 60m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rice (1 kg)",
                            Price = 55m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sugar (1 kg)",
                            Price = 45m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 8,
                            Name = "Salt (1 kg)",
                            Price = 20m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cooking Oil (1 L)",
                            Price = 130m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tea Powder (250 g)",
                            Price = 90m,
                            Stock = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
